import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

/** Postgres tsvector, read-only here: the column is generated by the database. */
const tsvector = customType<{ data: string }>({
  dataType() {
    return "tsvector";
  },
});

/**
 * contacts — the person behind each public form submission (written by
 * lib/lead-pipeline.ts) and their consent record: email, call/text,
 * unsubscribes. The team's CRM is Coldwell Banker's Home Platform; this table
 * is only the site's mirror.
 */
export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    fullName: text("full_name"),
    firstName: text("first_name"),
    lastName: text("last_name"),
    email: text("email"),
    phone: text("phone"),
    preferredChannel: text("preferred_channel"),

    type: text("type")
      .array()
      .default(sql`'{lead}'::text[]`),
    lifecycleStage: text("lifecycle_stage").default("new"),
    source: text("source"),
    sourceDetail: text("source_detail"),
    utm: jsonb("utm"),

    consentEmail: boolean("consent_email").default(false).notNull(),
    consentEmailAt: timestamp("consent_email_at", { withTimezone: true }),
    consentSms: boolean("consent_sms").default(false).notNull(),
    consentSmsAt: timestamp("consent_sms_at", { withTimezone: true }),
    consentSmsMethod: text("consent_sms_method"),
    unsubscribedEmail: boolean("unsubscribed_email").default(false).notNull(),
    unsubscribedSms: boolean("unsubscribed_sms").default(false).notNull(),
    doNotCall: boolean("do_not_call").default(false).notNull(),

    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    firstTouchAt: timestamp("first_touch_at", { withTimezone: true }),
    lastTouchAt: timestamp("last_touch_at", { withTimezone: true }),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
  },
  (table) => [
    index("contacts_lifecycle_stage_idx").on(table.lifecycleStage),
    index("contacts_email_idx").on(table.email),
  ],
);

/**
 * events — append-only activity log for contacts (form submits, unsubscribes).
 */
export const events = pgTable(
  "events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    eventType: text("event_type").notNull(),
    contactId: uuid("contact_id").references(() => contacts.id, {
      onDelete: "cascade",
    }),
    listingId: uuid("listing_id"),
    transactionId: uuid("transaction_id"),
    payload: jsonb("payload"),
    occurredAt: timestamp("occurred_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("events_contact_idx").on(table.contactId, table.occurredAt.desc()),
    index("events_type_idx").on(table.eventType, table.occurredAt.desc()),
  ],
);

/**
 * leads — one row per public form submission, written before any delivery is
 * attempted. This is the mirror of record: whatever the CRM, Zapier or Resend
 * do afterwards, the lead is here. `contact_id` links the contacts row;
 * `payload` is the exact JSON sent to the CRM webhook.
 *
 * `delivery_status` summarises the CRM attempt: 'pending' until tried,
 * 'delivered', 'failed', or 'skipped' (no provider configured).
 */
export const leads = pgTable(
  "leads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contactId: uuid("contact_id").references(() => contacts.id, {
      onDelete: "set null",
    }),
    form: text("form").notNull(),
    firstName: text("first_name"),
    lastName: text("last_name"),
    email: text("email").notNull(),
    phone: text("phone"),
    message: text("message"),
    market: text("market"),
    propertyAddress: text("property_address"),
    timing: text("timing"),
    sellFirst: text("sell_first"),
    consentEmail: boolean("consent_email").default(false).notNull(),
    consentSms: boolean("consent_sms").default(false).notNull(),
    consentAt: timestamp("consent_at", { withTimezone: true }),
    consentWordingVersion: text("consent_wording_version"),
    source: jsonb("source"),
    payload: jsonb("payload"),
    isTest: boolean("is_test").default(false).notNull(),
    deliveryStatus: text("delivery_status").default("pending").notNull(),
    deliveryError: text("delivery_error"),
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    submittedAt: timestamp("submitted_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("leads_submitted_idx").on(table.submittedAt.desc()),
    index("leads_email_idx").on(table.email),
    index("leads_delivery_status_idx")
      .on(table.deliveryStatus)
      .where(sql`${table.deliveryStatus} <> 'delivered'`),
  ],
);

/**
 * lead_deliveries — one row per sink per lead: what was tried, what came back.
 * sink: 'crm_webhook' | 'fub' | 'team_email' | 'plausible'.
 * status: 'ok' | 'failed' | 'skipped'.
 */
export const leadDeliveries = pgTable(
  "lead_deliveries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    leadId: uuid("lead_id")
      .references(() => leads.id, { onDelete: "cascade" })
      .notNull(),
    sink: text("sink").notNull(),
    status: text("status").notNull(),
    statusCode: integer("status_code"),
    attempts: integer("attempts").default(1).notNull(),
    detail: text("detail"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [index("lead_deliveries_lead_idx").on(table.leadId, table.createdAt.desc())],
);

/**
 * questionnaire_answers — the website questionnaire behind the private /q links.
 * One row per person per question; respondent is 'joelyn' or 'jessica'.
 * value is the free text, choice the picked option (null when none).
 * The ids and wording of the questions live in lib/questionnaire/questions.ts.
 */
export const questionnaireAnswers = pgTable(
  "questionnaire_answers",
  {
    respondent: text("respondent").notNull(),
    questionId: text("question_id").notNull(),
    value: text("value"),
    choice: text("choice"),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [primaryKey({ columns: [table.respondent, table.questionId] })],
);

/**
 * search_documents — the site search index (lib/search). One row per chunk of
 * the site's own content: a guide section, a neighborhood, a Tide issue part,
 * an Encore event or venue, a main page. id is stable and readable
 * ("guide:<slug>#<section>"); url carries the #anchor where there is one.
 * embedding is gte-small (384 dims, unit length) from the `embed` Edge
 * Function; fts is generated (title A, section_title B, body C, english).
 * content_hash decides what gets re-embedded. RLS on, no policies: the server
 * reads and writes through DATABASE_URL. Queried by search_scored() (0011).
 */
export const searchDocuments = pgTable(
  "search_documents",
  {
    id: text("id").primaryKey(),
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    sectionTitle: text("section_title"),
    url: text("url").notNull(),
    body: text("body").notNull(),
    contentHash: text("content_hash").notNull(),
    embedding: vector("embedding", { dimensions: 384 }),
    fts: tsvector("fts").generatedAlwaysAs(
      sql`setweight(to_tsvector('english'::regconfig, coalesce(title, '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce(section_title, '')), 'B') || setweight(to_tsvector('english'::regconfig, body), 'C')`,
    ),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    check("search_documents_kind_check", sql`${table.kind} in ('guide', 'neighborhood', 'post', 'event', 'venue', 'page')`),
    index("search_documents_embedding_idx").using("hnsw", table.embedding.op("vector_cosine_ops")),
    index("search_documents_fts_idx").using("gin", table.fts),
  ],
);

/**
 * newsletter_subscriptions — one address on one list (0013_newsletter.sql).
 * `email` is lowercased and unique per list: every form submission is its own
 * contacts row, so the subscription is keyed on the address, and `contact_id`
 * points at the latest row that asked. status: 'pending' (confirmation sent),
 * 'confirmed' (double opt-in done) or 'unsubscribed'. A contacts row with
 * `unsubscribed_email` for the same address overrides all of it: nothing is
 * sent to that address (lib/newsletter/state.ts).
 */
export const newsletterSubscriptions = pgTable(
  "newsletter_subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contactId: uuid("contact_id").references(() => contacts.id, { onDelete: "set null" }),
    email: text("email").notNull(),
    list: text("list").notNull(),
    status: text("status").notNull().default("pending"),
    /** The form that asked last: 'letter_form', 'calendar_form', 'contact_form', … */
    source: text("source"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow().notNull(),
    confirmationSentAt: timestamp("confirmation_sent_at", { withTimezone: true }),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
    welcomeSentAt: timestamp("welcome_sent_at", { withTimezone: true }),
    unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true }),
    /** 'link' (the page), 'one-click' (List-Unsubscribe-Post), 'all' (stop everything), 'manual'. */
    unsubscribeMethod: text("unsubscribe_method"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("newsletter_subscriptions_email_list_key").on(table.email, table.list),
    index("newsletter_subscriptions_list_status_idx").on(table.list, table.status),
    check("newsletter_subscriptions_list_check", sql`${table.list} in ('tide', 'encore')`),
    check("newsletter_subscriptions_status_check", sql`${table.status} in ('pending', 'confirmed', 'unsubscribed')`),
  ],
);

/**
 * issue_sends — one row per issue the site sends to subscribers: Tide per data
 * month (period 'YYYY-MM'), Encore per week (period = its Monday). Unique on
 * (kind, period), so a re-run of the hand-off never makes a second send.
 * status: 'scheduled' → 'sending' → 'sent'; 'held' by the team's link (or by
 * the system: a Fair Housing flag, a month that isn't complete, a missing
 * postal address) until someone presses "Send it now"; 'expired' when its
 * window passes unsent. The counts are from the latest run.
 */
export const issueSends = pgTable(
  "issue_sends",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: text("kind").notNull(),
    period: text("period").notNull(),
    periodLabel: text("period_label").notNull(),
    periodEnd: text("period_end").notNull(),
    subject: text("subject").notNull(),
    status: text("status").notNull().default("scheduled"),
    scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    heldBy: text("held_by"),
    holdReason: text("hold_reason"),
    heldAt: timestamp("held_at", { withTimezone: true }),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    recipients: integer("recipients").default(0).notNull(),
    sentCount: integer("sent_count").default(0).notNull(),
    failedCount: integer("failed_count").default(0).notNull(),
    unknownCount: integer("unknown_count").default(0).notNull(),
    deferredCount: integer("deferred_count").default(0).notNull(),
    lastError: text("last_error"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("issue_sends_kind_period_key").on(table.kind, table.period),
    index("issue_sends_status_idx").on(table.status, table.scheduledFor),
    check("issue_sends_kind_check", sql`${table.kind} in ('tide', 'encore')`),
    check("issue_sends_status_check", sql`${table.status} in ('scheduled', 'held', 'sending', 'sent', 'expired')`),
  ],
);

/**
 * newsletter_deliveries — every email sent to a subscriber: the confirmation,
 * the welcome and each issue, one row per address. For an issue the row is
 * written ('claimed') before the batch goes to Resend and is unique on
 * (issue_send_id, email), so two runs can't both send to one address.
 * status: 'claimed', 'sent', 'failed' (Resend said no; retried up to three
 * times) or 'unknown' (no clear answer; never retried automatically).
 * The rows sent today count against NEWSLETTER_DAILY_CAP.
 */
export const newsletterDeliveries = pgTable(
  "newsletter_deliveries",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: text("kind").notNull(),
    list: text("list").notNull(),
    subscriptionId: uuid("subscription_id").references(() => newsletterSubscriptions.id, { onDelete: "set null" }),
    issueSendId: uuid("issue_send_id").references(() => issueSends.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    status: text("status").notNull(),
    attempts: integer("attempts").default(1).notNull(),
    resendId: text("resend_id"),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    sentAt: timestamp("sent_at", { withTimezone: true }),
  },
  (table) => [
    uniqueIndex("newsletter_deliveries_issue_email_key").on(table.issueSendId, table.email),
    index("newsletter_deliveries_created_idx").on(table.createdAt),
    index("newsletter_deliveries_subscription_idx").on(table.subscriptionId),
    check("newsletter_deliveries_kind_check", sql`${table.kind} in ('confirmation', 'welcome', 'issue')`),
    check("newsletter_deliveries_status_check", sql`${table.status} in ('claimed', 'sent', 'failed', 'unknown')`),
  ],
);

export type Contact = typeof contacts.$inferSelect;
export type NewContact = typeof contacts.$inferInsert;
export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
export type LeadDelivery = typeof leadDeliveries.$inferSelect;
export type NewLeadDelivery = typeof leadDeliveries.$inferInsert;
export type QuestionnaireAnswer = typeof questionnaireAnswers.$inferSelect;
export type NewQuestionnaireAnswer = typeof questionnaireAnswers.$inferInsert;
export type NewsletterSubscription = typeof newsletterSubscriptions.$inferSelect;
export type IssueSend = typeof issueSends.$inferSelect;
export type NewsletterDelivery = typeof newsletterDeliveries.$inferSelect;
export type SearchDocument = typeof searchDocuments.$inferSelect;
export type NewSearchDocument = typeof searchDocuments.$inferInsert;

/* Encore (0012_encore.sql) lives in its own file. */
export * from "./encore-schema";
