/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  url?: string;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
  source?: string;
};

export type License = {
  _type: "license";
  name?: string;
  number?: string;
};

export type Highlight = {
  _type: "highlight";
  label?: string;
  description?: string;
};

export type Address = {
  _type: "address";
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brokerageName?: string;
  brokerageLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  officeAddress?: Address;
  licenses?: Array<
    {
      _key: string;
    } & License
  >;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  footerDisclosure?: string;
  mlsAttribution?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  ticker?: Array<string>;
  primaryPhoneDisplay?: string;
  primaryPhoneE164?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  attribution?: string;
  market?: "lakewood-ranch" | "sarasota" | "bradenton" | "tampa";
  date?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  edition?: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body?: BlockContent;
  publishedAt?: string;
  author?: TeamMemberReference;
  categories?: Array<string>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type VenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "venue";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  startsAt?: string;
  endsAt?: string;
  allDay?: boolean;
  venue?: VenueReference;
  category?: "music" | "theater" | "gallery" | "festival" | "family" | "market";
  ticketUrl?: string;
  priceNote?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  source?: string;
  sourceUrl?: string;
  featured?: boolean;
  description?: BlockContent;
};

export type NeighborhoodReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "neighborhood";
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  address?: Address;
  geo?: Geopoint;
  market?: "lakewood-ranch" | "sarasota" | "bradenton" | "tampa";
  neighborhood?: NeighborhoodReference;
  website?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  about?: BlockContent;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Listing = {
  _id: string;
  _type: "listing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  address?: Address;
  geo?: Geopoint;
  market?: "lakewood-ranch" | "sarasota" | "bradenton" | "tampa";
  price?: number;
  beds?: number;
  baths?: number;
  sqft?: number;
  status?: "active" | "pending" | "sold";
  tag?:
    | "new"
    | "coming-soon"
    | "just-reduced"
    | "under-contract"
    | "sold"
    | "off-market"
    | "open-house";
  featured?: boolean;
  soldDate?: string;
  percentOfList?: number;
  hero?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "photo";
    _key: string;
  }>;
  description?: BlockContent;
  features?: Array<string>;
  mlsNumber?: string;
  neighborhood?: NeighborhoodReference;
  agent?: TeamMemberReference;
  lotAcres?: number;
  yearBuilt?: number;
  renovated?: string;
  listedAt?: string;
  daysOnMarket?: number;
  floodZone?: string;
  annualTaxes?: number;
  openHouse?: string;
  cardNote?: string;
  friendNote?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  headshot?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  licenseNumber?: string;
  bio?: BlockContent;
  phone?: string;
  phoneE164?: string;
  email?: string;
  order?: number;
  register?: string;
  quote?: string;
};

export type ListingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "listing";
};

export type Neighborhood = {
  _id: string;
  _type: "neighborhood";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  market?: "lakewood-ranch" | "sarasota" | "bradenton" | "tampa";
  tagline?: string;
  hero?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  overview?: BlockContent;
  highlights?: Array<
    {
      _key: string;
    } & Highlight
  >;
  stat?: Stat;
  featuredListings?: Array<
    {
      _key: string;
    } & ListingReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | SocialLink
  | Stat
  | License
  | Highlight
  | Address
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | TeamMemberReference
  | Post
  | Slug
  | VenueReference
  | Event
  | NeighborhoodReference
  | Venue
  | Geopoint
  | Listing
  | TeamMember
  | ListingReference
  | Neighborhood
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries.ts
// Variable: listingsQuery
// Query: *[_type == "listing" && defined(slug.current)] | order(featured desc, listedAt desc) {  _id, title, "slug": slug.current, address, geo, price, beds, baths, sqft, status, tag, market,  lotAcres, yearBuilt, renovated, listedAt, daysOnMarket, floodZone, annualTaxes, cardNote,  friendNote, percentOfList, openHouse, mlsNumber, featured, soldDate, description, features,  "hero": hero {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "gallery": gallery[] {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "neighborhood": neighborhood->{ name, "slug": slug.current },  "agent": agent->{ name, "slug": slug.current }}
export type ListingsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  address: Address | null;
  geo: Geopoint | null;
  price: number | null;
  beds: number | null;
  baths: number | null;
  sqft: number | null;
  status: "active" | "pending" | "sold" | null;
  tag:
    | "coming-soon"
    | "just-reduced"
    | "new"
    | "off-market"
    | "open-house"
    | "sold"
    | "under-contract"
    | null;
  market: "bradenton" | "lakewood-ranch" | "sarasota" | "tampa" | null;
  lotAcres: number | null;
  yearBuilt: number | null;
  renovated: string | null;
  listedAt: string | null;
  daysOnMarket: number | null;
  floodZone: string | null;
  annualTaxes: number | null;
  cardNote: string | null;
  friendNote: string | null;
  percentOfList: number | null;
  openHouse: string | null;
  mlsNumber: string | null;
  featured: boolean | null;
  soldDate: string | null;
  description: BlockContent | null;
  features: Array<string> | null;
  hero: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  gallery: Array<{
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  }> | null;
  neighborhood: {
    name: string | null;
    slug: string | null;
  } | null;
  agent: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: eventsQuery
// Query: *[_type == "event" && defined(slug.current) && defined(venue)] | order(startsAt asc) {  _id, title, "slug": slug.current, summary, startsAt, endsAt, allDay, category, ticketUrl,  priceNote, source, sourceUrl, featured, description,  "image": image {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "venue": venue->{ name, "slug": slug.current, market, address, geo }}
export type EventsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  startsAt: string | null;
  endsAt: string | null;
  allDay: boolean | null;
  category:
    "family" | "festival" | "gallery" | "market" | "music" | "theater" | null;
  ticketUrl: string | null;
  priceNote: string | null;
  source: string | null;
  sourceUrl: string | null;
  featured: boolean | null;
  description: BlockContent | null;
  image: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  venue: {
    name: string | null;
    slug: string | null;
    market: "bradenton" | "lakewood-ranch" | "sarasota" | "tampa" | null;
    address: Address | null;
    geo: Geopoint | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: venuesQuery
// Query: *[_type == "venue" && defined(slug.current)] | order(name asc) {  _id, name, "slug": slug.current, address, geo, website, market, about,  "image": image {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "neighborhood": neighborhood->{ name, "slug": slug.current }}
export type VenuesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  address: Address | null;
  geo: Geopoint | null;
  website: string | null;
  market: "bradenton" | "lakewood-ranch" | "sarasota" | "tampa" | null;
  about: BlockContent | null;
  image: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  neighborhood: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: neighborhoodsQuery
// Query: *[_type == "neighborhood" && defined(slug.current)] | order(name asc) {  _id, name, "slug": slug.current, market, tagline, overview, highlights, stat,  "hero": hero {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "featuredListings": featuredListings[]->slug.current}
export type NeighborhoodsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  market: "bradenton" | "lakewood-ranch" | "sarasota" | "tampa" | null;
  tagline: string | null;
  overview: BlockContent | null;
  highlights: Array<
    {
      _key: string;
    } & Highlight
  > | null;
  stat: Stat | null;
  hero: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  featuredListings: Array<string | null> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc) {  _id, title, "slug": slug.current, excerpt, body, publishedAt, categories, edition,  "cover": cover {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "author": author->{ name, "slug": slug.current }}
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  categories: Array<string> | null;
  edition: string | null;
  cover: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: teamQuery
// Query: *[_type == "teamMember" && defined(slug.current)] | order(order asc) {  _id, name, "slug": slug.current, title, licenseNumber, bio, phone, phoneE164, email, order, register, quote,  "headshot": headshot {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }}}
export type TeamQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  title: string | null;
  licenseNumber: string | null;
  bio: BlockContent | null;
  phone: string | null;
  phoneE164: string | null;
  email: string | null;
  order: number | null;
  register: string | null;
  quote: string | null;
  headshot: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(_createdAt desc) {  _id, quote, attribution, market, date}
export type TestimonialsQueryResult = Array<{
  _id: string;
  quote: string | null;
  attribution: string | null;
  market: "bradenton" | "lakewood-ranch" | "sarasota" | "tampa" | null;
  date: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {  brokerageName, officeAddress, licenses, socialLinks, footerDisclosure, mlsAttribution,  stats, ticker, primaryPhoneE164, primaryPhoneDisplay,  "brokerageLogo": brokerageLogo {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }},  "defaultOgImage": defaultOgImage {  alt, hotspot, crop,  asset->{ url, metadata { dimensions { width, height }, lqip } }}}
export type SiteSettingsQueryResult = {
  brokerageName: string | null;
  officeAddress: Address | null;
  licenses: Array<
    {
      _key: string;
    } & License
  > | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  footerDisclosure: string | null;
  mlsAttribution: string | null;
  stats: Array<
    {
      _key: string;
    } & Stat
  > | null;
  ticker: Array<string> | null;
  primaryPhoneE164: string | null;
  primaryPhoneDisplay: string | null;
  brokerageLogo: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
  defaultOgImage: {
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: staleEventIdsQuery
// Query: *[_type == "event" && dateTime(coalesce(endsAt, startsAt)) < dateTime($cutoff)]._id
export type StaleEventIdsQueryResult = Array<string>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "listing" && defined(slug.current)] | order(featured desc, listedAt desc) {\n  _id, title, "slug": slug.current, address, geo, price, beds, baths, sqft, status, tag, market,\n  lotAcres, yearBuilt, renovated, listedAt, daysOnMarket, floodZone, annualTaxes, cardNote,\n  friendNote, percentOfList, openHouse, mlsNumber, featured, soldDate, description, features,\n  "hero": hero {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "gallery": gallery[] {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "neighborhood": neighborhood->{ name, "slug": slug.current },\n  "agent": agent->{ name, "slug": slug.current }\n}': ListingsQueryResult;
    '*[_type == "event" && defined(slug.current) && defined(venue)] | order(startsAt asc) {\n  _id, title, "slug": slug.current, summary, startsAt, endsAt, allDay, category, ticketUrl,\n  priceNote, source, sourceUrl, featured, description,\n  "image": image {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "venue": venue->{ name, "slug": slug.current, market, address, geo }\n}': EventsQueryResult;
    '*[_type == "venue" && defined(slug.current)] | order(name asc) {\n  _id, name, "slug": slug.current, address, geo, website, market, about,\n  "image": image {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "neighborhood": neighborhood->{ name, "slug": slug.current }\n}': VenuesQueryResult;
    '*[_type == "neighborhood" && defined(slug.current)] | order(name asc) {\n  _id, name, "slug": slug.current, market, tagline, overview, highlights, stat,\n  "hero": hero {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "featuredListings": featuredListings[]->slug.current\n}': NeighborhoodsQueryResult;
    '*[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc) {\n  _id, title, "slug": slug.current, excerpt, body, publishedAt, categories, edition,\n  "cover": cover {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "author": author->{ name, "slug": slug.current }\n}': PostsQueryResult;
    '*[_type == "teamMember" && defined(slug.current)] | order(order asc) {\n  _id, name, "slug": slug.current, title, licenseNumber, bio, phone, phoneE164, email, order, register, quote,\n  "headshot": headshot {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n}\n}': TeamQueryResult;
    '*[_type == "testimonial"] | order(_createdAt desc) {\n  _id, quote, attribution, market, date\n}': TestimonialsQueryResult;
    '*[_type == "siteSettings"][0] {\n  brokerageName, officeAddress, licenses, socialLinks, footerDisclosure, mlsAttribution,\n  stats, ticker, primaryPhoneE164, primaryPhoneDisplay,\n  "brokerageLogo": brokerageLogo {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n},\n  "defaultOgImage": defaultOgImage {\n  alt, hotspot, crop,\n  asset->{ url, metadata { dimensions { width, height }, lqip } }\n}\n}': SiteSettingsQueryResult;
    '*[_type == "event" && dateTime(coalesce(endsAt, startsAt)) < dateTime($cutoff)]._id': StaleEventIdsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
