import type { Listing } from "../types";
import { img, p } from "./helpers";

/**
 * Sample inventory. Eight records across the three places: seven active
 * (one coming soon), one under contract, two sold. Copy follows the brand
 * voice: what is unusual, what was rebuilt and when, what the street is like.
 * Numbers are illustrative and carry no MLS provenance until Sanity replaces them.
 */
export const LISTINGS: Listing[] = [
  {
    _id: "listing-18-cliffside-terrace",
    title: "18 Cliffside Terrace",
    slug: "18-cliffside-terrace-lakewood-ranch",
    address: { street: "18 Cliffside Terrace", city: "Lakewood Ranch", state: "FL", zip: "34202" },
    geo: { lat: 27.4021, lng: -82.4189 },
    price: 2_850_000,
    beds: 4,
    baths: 3.5,
    sqft: 3940,
    lotAcres: 0.42,
    yearBuilt: 2004,
    renovated: "Kitchen 2019",
    status: "active",
    tag: "new",
    market: "lakewood-ranch",
    neighborhood: { name: "The Lake Club", slug: "lake-club" },
    agent: { name: "Joelyn Nauman", slug: "joelyn-nauman" },
    mlsNumber: "A4417290",
    listedAt: "2026-09-03",
    daysOnMarket: 2,
    floodZone: "X",
    annualTaxes: 14_200,
    featured: true,
    cardNote: "LAKEFRONT · POOL",
    hero: img("library/listing-hero-estate-twilight", "18 Cliffside Terrace at twilight", "62% 58%"),
    gallery: [
      img("library/listing-kitchen-4pm-island", "The kitchen at four in the afternoon"),
      img("library/listing-living-room-terrazzo", "Living room with terrazzo floors"),
      img("library/listing-primary-bath-terrazzo", "Primary bath with a freestanding tub"),
      img("library/lwr-lakefront-row", "The lakefront from the lanai"),
      img("library/listing-aerial-lot-morning", "Aerial view of the lot in the morning"),
    ],
    description: p(
      "Water views from three levels, a kitchen rebuilt in 2019, and the good end of the street. Four similar homes sold here last year, all inside nine days.",
      "The lot backs to the lake with western exposure, so the lanai gets the evening light and the parcel behind it is deed-restricted open space. The primary suite is on the main level; three bedrooms and a study are upstairs.",
      "Cliffside Terrace is a cul-de-sac of fourteen homes inside The Lake Club gate, two minutes from the clubhouse and eleven from Main Street.",
    ),
    features: [
      "Lakefront, western exposure",
      "Kitchen rebuilt 2019, 48-inch range",
      "Primary suite on the main level",
      "Heated saltwater pool and spa",
      "Impact glass throughout",
      "Whole-house generator, 2022",
      "Three-car garage",
    ],
    friendNote:
      "The lake side of the street gets the evening light and the view will not change; the parcel behind is preserve. The two active listings nearby are priced higher for less water. If you need to be in by August, this one closes clean; the sellers have already moved.",
  },
  {
    _id: "listing-7104-waterside-way",
    title: "7104 Waterside Way",
    slug: "7104-waterside-way-lakewood-ranch",
    address: { street: "7104 Waterside Way", city: "Lakewood Ranch", state: "FL", zip: "34240" },
    geo: { lat: 27.3961, lng: -82.4082 },
    price: 1_150_000,
    beds: 3,
    baths: 2.5,
    sqft: 2410,
    lotAcres: 0.21,
    yearBuilt: 2019,
    status: "active",
    tag: "just-reduced",
    market: "lakewood-ranch",
    county: "Sarasota County",
    neighborhood: { name: "Waterside", slug: "waterside" },
    agent: { name: "Jessica Garza", slug: "jessica-garza" },
    mlsNumber: "A4419112",
    listedAt: "2026-08-05",
    daysOnMarket: 31,
    floodZone: "X",
    annualTaxes: 9_800,
    featured: true,
    cardNote: "LAKE VIEW · 2019",
    hero: img("library/lwr-lakefront-row", "7104 Waterside Way from the lake"),
    gallery: [
      img("library/interior-living-room", "The living room"),
      img("library/listing-kitchen-4pm-island", "The kitchen island"),
      img("library/lwr-waterside-promenade", "Waterside Place, a ten-minute walk"),
    ],
    description: p(
      "Down to $1,150,000 from $1,295,000. Thirty-one days told us the first number was wrong, so we moved it.",
      "A 2019 build on the Kingfisher Lake side of Waterside, with the lanai facing water and the promenade a ten-minute walk along the shore. Three bedrooms on one level, a den off the entry, and the two-car garage has a 240-volt outlet.",
      "Waterside Way is the loop road nearest the town center. Sidewalks on both sides, and the Sunday market is close enough to hear the band.",
    ),
    features: [
      "Lake view from the lanai",
      "Built 2019, tile roof",
      "Den off the entry",
      "Gas cooktop, quartz counters",
      "240-volt outlet in the garage",
      "Walk to Waterside Place",
    ],
    friendNote:
      "The first price was the seller's, not ours. At $1,150,000 it is now under the two comparable sales from the spring, and it shows better than both. Expect a second showing to be busy.",
  },
  {
    _id: "listing-312-riverwalk-court",
    title: "312 Riverwalk Court",
    slug: "312-riverwalk-court-siesta-key",
    address: { street: "312 Riverwalk Court", city: "Sarasota", state: "FL", zip: "34242" },
    geo: { lat: 27.2831, lng: -82.5505 },
    price: 3_400_000,
    beds: 5,
    baths: 4,
    sqft: 4620,
    lotAcres: 0.38,
    yearBuilt: 2008,
    renovated: "Seawall and dock 2023",
    status: "active",
    tag: "new",
    market: "sarasota",
    neighborhood: { name: "Siesta Key", slug: "siesta-key" },
    agent: { name: "Joelyn Nauman", slug: "joelyn-nauman" },
    mlsNumber: "A4420077",
    listedAt: "2026-09-01",
    daysOnMarket: 4,
    floodZone: "AE",
    annualTaxes: 21_400,
    featured: true,
    cardNote: "POOL · DOCK",
    hero: img("library/listing-twilight-exterior-pool", "312 Riverwalk Court, pool at twilight"),
    gallery: [
      img("library/listing-dock-view-sunset", "The dock at sunset"),
      img("library/moment-poolside", "Poolside in the late afternoon"),
      img("library/interior-jalousie", "Jalousie windows in the morning room"),
      img("library/listing-living-room-terrazzo", "Living room, terrazzo floors"),
    ],
    description: p(
      "A deep-water canal on the north end of Siesta Key, a seawall and dock rebuilt in 2023, and a lift rated for a 30-footer. The pool faces west over the water.",
      "Five bedrooms across two levels, with the primary and a guest suite downstairs. The kitchen opens to the lanai through pocketing sliders; the second floor has a balcony the length of the house.",
      "Riverwalk Court is a dead-end street of nine waterfront lots, three minutes from the north bridge and eight from the village.",
    ),
    features: [
      "Deep-water canal, no bridges to the bay",
      "Seawall and dock rebuilt 2023, 16,000-lb lift",
      "West-facing pool and spa",
      "Two suites on the main level",
      "Pocketing sliders to the lanai",
      "Metal roof 2021",
      "Elevated construction, flood zone AE",
    ],
    friendNote:
      "The seawall was inspected in March and has ten years left. The dock is deep enough for a 30-footer at low tide, which is rarer on this canal than the listing photos suggest. The two active listings nearby are priced higher for less water.",
  },
  {
    _id: "listing-4419-bayshore-lane",
    title: "4419 Bayshore Lane",
    slug: "4419-bayshore-lane-bradenton",
    address: { street: "4419 Bayshore Lane", city: "Bradenton", state: "FL", zip: "34210" },
    geo: { lat: 27.4436, lng: -82.6161 },
    price: 975_000,
    beds: 3,
    baths: 2,
    sqft: 1980,
    lotAcres: 0.24,
    yearBuilt: 1972,
    renovated: "Roof 2022, kitchen 2020",
    status: "active",
    market: "bradenton",
    neighborhood: { name: "West Bradenton", slug: "west-bradenton" },
    agent: { name: "Jessica Garza", slug: "jessica-garza" },
    mlsNumber: "A4421540",
    listedAt: "2026-09-01",
    daysOnMarket: 4,
    floodZone: "X",
    annualTaxes: 6_900,
    featured: true,
    cardNote: "CANAL · FLOOD ZONE X",
    hero: img("library/bradenton-canal-ranch-twilight", "4419 Bayshore Lane at twilight"),
    gallery: [
      img("library/listing-exterior-canal-golden", "The canal side at golden hour"),
      img("library/interior-jalousie", "The Florida room"),
      img("library/listing-kitchen-4pm-island", "Kitchen, renovated 2020"),
    ],
    description: p(
      "A 1972 ranch on a canal west of 75th, in flood zone X, which is the sentence that matters. Roof in 2022, kitchen in 2020, and the original terrazzo under the carpet in two bedrooms.",
      "Three bedrooms on one level with a Florida room across the back and a dock at the seawall. The canal runs out to Palma Sola Bay in about ten minutes at idle.",
      "Bayshore Lane is one of the older canal streets, wide lots and no HOA, with the Anna Maria bridge eight minutes away.",
    ),
    features: [
      "Canal front, dock and seawall",
      "Flood zone X",
      "Roof 2022",
      "Kitchen 2020",
      "Terrazzo under the carpet",
      "No HOA",
    ],
    friendNote:
      "Four days in and it has had eleven showings. The zone X designation is the reason: insurance quotes are coming in under $2,000, which on this water is unusual. The Florida room is not under air; budget for that.",
  },
  {
    _id: "listing-5501-country-club-way",
    title: "5501 Country Club Way",
    slug: "5501-country-club-way-lakewood-ranch",
    address: { street: "5501 Country Club Way", city: "Lakewood Ranch", state: "FL", zip: "34202" },
    geo: { lat: 27.4098, lng: -82.4012 },
    price: 1_695_000,
    beds: 4,
    baths: 3,
    sqft: 3120,
    lotAcres: 0.31,
    yearBuilt: 2015,
    status: "active",
    tag: "coming-soon",
    market: "lakewood-ranch",
    neighborhood: { name: "Country Club East", slug: "country-club-east" },
    agent: { name: "Joelyn Nauman", slug: "joelyn-nauman" },
    mlsNumber: "A4422019",
    listedAt: "2026-09-12",
    daysOnMarket: 0,
    floodZone: "X",
    annualTaxes: 12_100,
    featured: false,
    cardNote: "GOLF VIEW · 2015",
    hero: img("library/listing-aerial-lot-morning", "5501 Country Club Way from above, in the morning"),
    gallery: [
      img("library/listing-living-room-terrazzo", "The great room"),
      img("library/listing-primary-bath-terrazzo", "The primary bath"),
    ],
    description: p(
      "Photography is scheduled for next week; showings begin the day it goes active on the MLS. A 2015 build on the seventh fairway inside Country Club East, with a pool, a summer kitchen and a three-car garage.",
      "Four bedrooms, three baths, and a bonus room over the garage. The lanai faces south-west across the fairway to the preserve.",
    ),
    features: [
      "Golf course view, seventh fairway",
      "Built 2015",
      "Pool and summer kitchen",
      "Bonus room over the garage",
      "Three-car garage",
    ],
    friendNote:
      "We will have the price on Friday. Tell us the timing and we will hold a slot in the first week it is active.",
  },
  {
    _id: "listing-9-sea-oats-court",
    title: "9 Sea Oats Court",
    slug: "9-sea-oats-court-anna-maria",
    address: { street: "9 Sea Oats Court", city: "Anna Maria", state: "FL", zip: "34216" },
    geo: { lat: 27.5305, lng: -82.7339 },
    price: 2_195_000,
    beds: 4,
    baths: 3,
    sqft: 2640,
    lotAcres: 0.19,
    yearBuilt: 2016,
    status: "pending",
    tag: "under-contract",
    market: "bradenton",
    neighborhood: { name: "Anna Maria Island", slug: "anna-maria-island" },
    agent: { name: "Jessica Garza", slug: "jessica-garza" },
    mlsNumber: "A4418800",
    listedAt: "2026-07-18",
    daysOnMarket: 22,
    floodZone: "AE",
    annualTaxes: 16_300,
    featured: false,
    cardNote: "BEACH · 2016",
    hero: img("library/place-sea-oats-dusk", "Sea oats on the dunes at dusk, two houses from the beach"),
    gallery: [img("library/place-sea-oats-wind", "The dune path to the beach")],
    description: p(
      "Two houses from the beach access on the north end of Anna Maria, built in 2016 to the current elevation code. Under contract after twenty-two days.",
      "Four bedrooms over two elevated levels, a pool under the house, and a roof deck that sees the Gulf and the Skyway.",
    ),
    features: ["Two houses from the beach", "Built 2016 to elevation code", "Roof deck, Gulf view", "Pool under the house"],
  },
  {
    _id: "listing-2210-oak-canopy-lane",
    title: "2210 Oak Canopy Lane",
    slug: "2210-oak-canopy-lane-sarasota",
    address: { street: "2210 Oak Canopy Lane", city: "Sarasota", state: "FL", zip: "34239" },
    geo: { lat: 27.3161, lng: -82.5301 },
    price: 1_425_000,
    beds: 3,
    baths: 2.5,
    sqft: 2380,
    lotAcres: 0.28,
    yearBuilt: 1958,
    renovated: "Addition 2017",
    status: "sold",
    tag: "sold",
    soldDate: "2026-06-12",
    percentOfList: 100,
    market: "sarasota",
    neighborhood: { name: "West of the Trail", slug: "west-of-the-trail" },
    agent: { name: "Joelyn Nauman", slug: "joelyn-nauman" },
    mlsNumber: "A4409922",
    listedAt: "2026-05-15",
    daysOnMarket: 14,
    floodZone: "X",
    featured: false,
    cardNote: "SOLD · 14 DAYS",
    hero: img("library/place-oak-canopy", "Oak Canopy Lane under its trees"),
    gallery: [],
    description: p(
      "A 1958 block house west of the Trail with a 2017 addition that doubled the kitchen. Sold at asking in fourteen days, June 2026.",
    ),
    features: ["Sold June 2026", "Addition 2017"],
  },
  {
    _id: "listing-308-riverwalk-court",
    title: "308 Riverwalk Court",
    slug: "308-riverwalk-court-siesta-key",
    address: { street: "308 Riverwalk Court", city: "Sarasota", state: "FL", zip: "34242" },
    geo: { lat: 27.2833, lng: -82.5509 },
    price: 3_120_000,
    beds: 4,
    baths: 3.5,
    sqft: 3880,
    lotAcres: 0.36,
    yearBuilt: 2004,
    status: "sold",
    tag: "sold",
    soldDate: "2026-05-02",
    percentOfList: 104,
    market: "sarasota",
    neighborhood: { name: "Siesta Key", slug: "siesta-key" },
    // Sold by another brokerage; shown as market evidence, not as the team's sale.
    mlsNumber: "A4408117",
    listedAt: "2026-04-10",
    daysOnMarket: 9,
    floodZone: "AE",
    featured: false,
    cardNote: "SOLD · 104% OF LIST",
    hero: img("library/listing-dock-view-sunset", "The dock at 308 Riverwalk Court at sunset"),
    gallery: [],
    description: p(
      "Sold in nine days at 104 percent of list, May 2026. Priced right, this street clears asking.",
    ),
    features: ["Sold May 2026", "104% of list price", "Nine days on market"],
  },
];
